# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: banner.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x62\x61nner.proto\"\xc2\x02\n\nBannerInfo\x12,\n\nGarena_420\x18\x01 \x03(\x0b\x32\x18.BannerInfo.SupportEntry\x1a\x85\x02\n\x0cSupportEntry\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\x05\x12\r\n\x05title\x18\x03 \x01(\t\x12\x10\n\x08imageUrl\x18\x05 \x01(\t\x12\x13\n\x0bimageUrlAlt\x18\x07 \x01(\t\x12\x13\n\x0bsupportLink\x18\x08 \x01(\t\x12\x0f\n\x07message\x18\t \x01(\t\x12\x11\n\tstartTime\x18\n \x01(\x03\x12\x0f\n\x07\x65ndTime\x18\x0b \x01(\x03\x12\x0e\n\x06region\x18\x0c \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\r \x01(\x05\x12\x13\n\x0bsubcategory\x18\x0e \x01(\x05\x12\x10\n\x08priority\x18\x13 \x01(\x05\x12\x12\n\nsurveyLink\x18\x14 \x01(\t\"\xf2\x01\n\tEventInfo\x12)\n\nGarena_420\x18\x01 \x03(\x0b\x32\x15.EventInfo.EventEntry\x1a\xb9\x01\n\nEventEntry\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x0c\n\x04\x63ode\x18\x03 \x01(\x05\x12\r\n\x05title\x18\x04 \x01(\t\x12\x12\n\ninternalId\x18\x05 \x01(\x05\x12\x11\n\tstartTime\x18\x06 \x01(\x03\x12\x0f\n\x07\x65ndTime\x18\x07 \x01(\x03\x12\x10\n\x08imageUrl\x18\x08 \x01(\t\x12\x0e\n\x06status\x18\t \x01(\x05\x12\x0c\n\x04link\x18\x0c \x01(\t\x12\x0c\n\x04\x66lag\x18\x11 \x01(\x05\"\x86\x01\n\tOtherInfo\x12)\n\nGarena_420\x18\x01 \x03(\x0b\x32\x15.OtherInfo.OtherEntry\x1aN\n\nOtherEntry\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04type\x18\x02 \x01(\x05\x12\x17\n\nadditional\x18\x03 \x01(\x05H\x00\x88\x01\x01\x42\r\n\x0b_additional\"b\n\nGarena_420\x12\x1c\n\x07\x42\x61nners\x18\x01 \x01(\x0b\x32\x0b.BannerInfo\x12\x1a\n\x06\x45vents\x18\x02 \x01(\x0b\x32\n.EventInfo\x12\x1a\n\x06Others\x18\x03 \x01(\x0b\x32\n.OtherInfob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'banner_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_BANNERINFO']._serialized_start=17
  _globals['_BANNERINFO']._serialized_end=339
  _globals['_BANNERINFO_SUPPORTENTRY']._serialized_start=78
  _globals['_BANNERINFO_SUPPORTENTRY']._serialized_end=339
  _globals['_EVENTINFO']._serialized_start=342
  _globals['_EVENTINFO']._serialized_end=584
  _globals['_EVENTINFO_EVENTENTRY']._serialized_start=399
  _globals['_EVENTINFO_EVENTENTRY']._serialized_end=584
  _globals['_OTHERINFO']._serialized_start=587
  _globals['_OTHERINFO']._serialized_end=721
  _globals['_OTHERINFO_OTHERENTRY']._serialized_start=643
  _globals['_OTHERINFO_OTHERENTRY']._serialized_end=721
  _globals['_GARENA_420']._serialized_start=723
  _globals['_GARENA_420']._serialized_end=821
# @@protoc_insertion_point(module_scope)
